# Uso de Python para construir el modelo

La idea es usar python para modificar el archivo de excel.

In [60]:
import pandas as pd
import numpy as np
# Cargar las hojas del excel como data frame separados
file_xls= 'modelData.xls'
PstKB_OF_sheet='PstKB_OF'
PstKB_OF_columns = ['NaN','ID','KB','Reaction Name','Molecule','NaN']
PstKB_OF = pd.read_excel(file_xls,sheet_name=code_sheet, header=None, names=PstKB_OF_columns)
biomass3_sheet ='biomass3.1'
biomass3_columns = ['KB','Changes Guevara']
biomass3 = pd.read_excel(file_xls,sheet_name=biomass3_sheet,names=biomass3_columns) 

# Dividir las columnas 'KB' y 'Changes Guevara' y crear nuevas columnas
split_columns = biomass3['KB'].str.split(expand=True)
biomass3['Metabolito'] = split_columns[0]  # Assuming the Metabolito column is the first one after the split
biomass3['KB'] = split_columns[1]
split_columns = biomass3['Changes Guevara'].str.split(expand=True)
biomass3['Changes Metabolito'] = split_columns[0]  # Assuming the Changes Metabolito column is the first one after the split
biomass3['Changes Guevara'] = split_columns[1]
biomass3.columns = ['Metabolito','Metabolito-G','KB','Guevara']
# Fusionar las columnas 'Metabolito' y 'Metabolito-G' en una nueva columna llamada 'Metabolito-Total'
biomass3['ID'] = biomass3['Metabolito'].combine_first(biomass3['Metabolito-G'])
# Eliminar las columnas originales 'Metabolito' y 'Metabolito-G' si así lo deseas
biomass3 = biomass3.drop(['Metabolito', 'Metabolito-G'], axis=1)
# Reorganizar las columnas del DataFrame
biomass3 = biomass3[['ID', 'KB', 'Guevara']]

In [64]:
extractSec = PstKB_OF[['ID','Reaction Name']]

mergeDf = pd.merge(extractSec, biomass3, on='ID', how='inner')
mergeDf

              ID Reaction Name       KB  Guevara
0   cpd00001[c0]       H2O_c0,       30   52.486
1   cpd00003[c0]       NAD_c0,   0.0003   0.0003
2   cpd00002[c0]       ATP_c0,   30.027   50.864
3   cpd00006[c0]      NADP_c0,  0.00013  0.00013
4   cpd00004[c0]      NADH_c0,  0.00015  0.00015
..           ...           ...      ...      ...
68  cpd00012[c0]       PPi_c0,    0.218    0.218
69  cpd00067[c0]        H+_c0,       30       30
70  cpd00008[c0]       ADP_c0,       30       30
71  cpd00014[c0]       UDP_c0,    0.766    0.766
72  cpd11416[c0]   Biomass_c0,      NaN      NaN

[73 rows x 4 columns]

In [68]:
# Guardar el nuevo DataFrame en un archivo CSV
mergeDf.to_csv('Code.csv', index=False)

## Cargar la tabla comparativa
Dentro del archivo hay una tabla comparativa entre 3 modelos Botero, Guevara y PstKB

In [67]:
Comparative_sheet='Comparative OFs'
Comparative_colums = ['Metabolito', 'Guevara 2023','Botero 2018','PstKB_Ori','PstKB_cobra']
comp_Table= pd.read_excel(file_xls,sheet_name=Comparative_sheet,names=Comparative_colums)
comp_Table = comp_Table[['Metabolito','Botero 2018','Guevara 2023','PstKB_Ori','PstKB_cobra']]
comp_Table

,Metabolito,Botero 2018,Guevara 2023,PstKB_Ori,PstKB_cobra
0,dATP,0.0027,0.028881,0.030000,0.028881
1,dTTP,0.0028,0.028881,NaN,NaN
2,dCTP,0.0018,0.015417,0.026000,0.015417
3,dGTP,0.00166,0.015417,0.026000,0.015417
4,UTP,0.0028,0.095373,0.027000,0.095373
5,CTP,0.0032,0.050418,NaN,NaN
6,GTP,0.0039,0.059181,NaN,NaN
7,alanine,0.107,0.125715,0.161000,0.125715
8,cysteine,0.024,0.023571,NaN,NaN
9,aspartic acid,0.162,0.0922,NaN,NaN
10,glutamic acid,0.39,0.113681,0.130000,0.113681
11,phenylalanine,0.08,0.066998,NaN,NaN
12,glycine,0.14,0.119759,NaN,NaN
13,histidine,-,0.034132,NaN,NaN
14,isoleucine,0.06,0.089036,NaN,NaN
15,lysine,0.001,0.111221,0.096000,NaN
16,leucine,0.14,0.149333,NaN,NaN
17,methionine,0.002,0.038393,0.049000,0.038393
18,asparagine,0.39,0.070447,NaN,NaN
19,proline,0.01,0.084621,NaN,NaN
20,glutamine,0.35,0.059905,0.071000,0.059905
21,arginine,-,0.083304,NaN,NaN
22,serine,0.21,0.136486,NaN,NaN
23,threonine,0.086,0.084449,NaN,NaN
24,valine,-,0.115457,NaN,NaN
25,tryptophan,0.04,0.018506,NaN,NaN
26,tyrosine,0.03,0.048038,NaN,NaN
27,palmitoleic acid,1,0.04043,NaN,NaN
28,palmitic acid,-,0.000304,NaN,NaN
29,linolenic acid,-,0.118671,NaN,NaN
30,linoleic acid,-,0.040003,NaN,NaN
31,stearic acid,-,0.000455,NaN,NaN
32,oleic acid,-,0.003467,NaN,NaN
33,ATP,1,50.86403,-30.027000,50.86403
34,H2O,-,52.486878,30.000000,52.486878
35,ADP,30,50.821625,NaN,NaN
36,Pi,30,50.821625,NaN,NaN
37,H+,NaN,50.821625,NaN,NaN
38,Ppi,NaN,0.251164,NaN,NaN
39,alpha-D-glucose,0.053,0.053,NaN,NaN
40,D-xylose,0.282,0.282,NaN,NaN
41,Coniferyl alcohol,0.048,0.048,NaN,NaN
42,synapyl alcohol,0.056,0.056,NaN,NaN
43,coumaryl alcohol,0.04,0.04,NaN,NaN
44,beta-D-fructose,0.053,-,NaN,NaN
45,sucrose,0.096,-,NaN,NaN
46,cellulose,0.305,-,NaN,NaN
47,starch,0.265,-,NaN,NaN
48,biomass,1,0** or 1*,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN
50,NAD,-,-,-0.000300,Not included in this version
51,NADP,NaN,NaN,0.000130,Not included in this version
52,NADH,NaN,NaN,0.000150,Not included in this version
53,NADPH,NaN,NaN,0.000100,Not included in this version
54,CoA,NaN,NaN,0.000136,Not included in this version
55,FAD,NaN,NaN,0.000100,NaN
56,Pyridoxal phosphate_c0,NaN,NaN,0.000100,NaN
57,S-Adenosyl-L-methionine,NaN,NaN,-0.000543,NaN